name: on push

on:
  push:
    branches:
      - '**'
      - '!task'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./
