name: on tag

on:
  push:
    branches:
      - '**'
      - '!task'
jobs:
  show-tag:
    runs-on: ubuntu-latest
    steps:
      - name: ref to tag
        id: ref
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"

      - name: tag
        env:
          REF: ${{ steps.ref.outputs.tag }}
          TAG: v1.0.1
        run: |
          echo ${GITHUB_REF##*/}
          echo ${{ env.TAG }} | sed -e "s/\./-/g"
          echo ${{ env.TAG }}