name: on tag

on:
  push:
    branches:
      - '**'
      - '!task'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
  show-tag:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: tag
        env:
          REF: ${{ github.ref }}
          TAG: v1.0.1
        run: |
          echo ${ GITHUB_REF##*/ }
          echo ${{ env.TAG }} | sed -e "s/\./-/g"
          echo ${{ env.TAG }}