name: on tag

on:
  push:
    branches:
      - '**'
      - '!task'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  calc-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.tag.outputs.tag}}
    steps:
      - name: get tag
        id: tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"
  use-tag:
    runs-on: ubuntu-latest
    needs: [calc-tag]
    steps:
      - name: use tag
        env:
          TAG: ${{ needs.calc-tag.outputs.tag }}
        run: |
          echo ${{ env.TAG }} | sed -e "s/\./-/g"
          echo ${{ env.TAG }}