name: on tag

on:
  push:
    branches:
      - '**'
      - '!task'
jobs:
  show-tag:
    runs-on: ubuntu-latest
    steps:
      - name: tag
        env:
          REF: ${{ github.ref }}
          REF_ENV: ${{ env.REF }}
          TAG: v1.0.1
        run: |
          echo $GITHUB_REF##*/
          echo ${{ env.TAG }} | sed -e "s/\./-/g"
          echo ${{ env.TAG }}