name: on tag

on:
  push:
    branches:
      - '**'
      - '!task'
jobs:
  show-tag:
    runs-on: ubuntu-latest
    steps:
      - name: tag
        id: tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"

      - name: result
        env:
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          echo ${{ env.TAG }} | sed -e "s/\./-/g"
          echo ${{ env.TAG }}